modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/DigitalItems/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="digitalitems"
version="${file.jarVersion}"
displayName="Digital Items"
displayURL="https://github.com/SirEdvin/DigitalItems/"

credits=""
authors=""
description='''
'''

[[dependencies.digitalitems]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.digitalitems]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.digitalitems]]
modId="peripheralium"
mandatory=true
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"