modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/SirEdvin/DigitalItems/issues"

[[mods]]
modId="digitalitems"
version="${file.jarVersion}"
displayName="Digital Items"
displayURL="https://github.com/SirEdvin/DigitalItems/"
logoFile="pack.png"
authors="SirEdvin"
description='''
Digitize items, fluids, and energy with ComputerCraft.
'''

[[dependencies.digitalitems]]
modId="neoforge"
type="required"
versionRange="[${neoforgeVersion},21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.digitalitems]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.digitalitems]]
modId="computercraft"
type="required"
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.digitalitems]]
modId="tweakium"
type="required"
versionRange="[${tweakiumVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.digitalitems]]
modId="broccolium"
type="required"
versionRange="[${broccoliumVersion},)"
ordering="NONE"
side="BOTH"
